Shaders:
  Lighting: "engine/resources/shaders/materials/lighting.chshader"
  Skinned: "engine/resources/shaders/materials/skinned.chshader"
  Unlit: "engine/resources/shaders/materials/unlit.chshader"
  Billboard: "engine/resources/shaders/materials/billboard.chshader"
  Sprite: "engine/resources/shaders/materials/sprite.chshader"
  ShadowDepth: "engine/resources/shaders/materials/shadow_depth.chshader"
  Skybox: "engine/resources/shaders/env/skybox.chshader"
  SkyboxCross: "engine/resources/shaders/env/skybox_cross.chshader"
  SkyboxCubemap: "engine/resources/shaders/env/skybox_cubemap.chshader"
  ColliderDebug: "engine/resources/shaders/debug/collider_debug.chshader"
  Grid: "engine/resources/shaders/debug/grid.chshader"
  PostProcess: "engine/resources/shaders/postfx/post_process.chshader"
